### ISSUE TITLE
environment from cli.rb example gives error

### ISSUE THREAD

**Issue by ymendel** [joshbuddy/optitron#2]
I'm trying the "environment" flag from the cli.rb example and I get the following error:

```
$ ./blah.rb install -e test
/Users/yossef/.rvm/gems/ruby-1.8.7-p249/gems/optitron-0.1.5/lib/optitron/option.rb:175:in `consume': unknown type: nil (RuntimeError)
  from /Users/yossef/.rvm/gems/ruby-1.8.7-p249/gems/optitron-0.1.5/lib/optitron/parser.rb:47:in `parse_options'
  from /Users/yossef/.rvm/gems/ruby-1.8.7-p249/gems/optitron-0.1.5/lib/optitron/parser.rb:43:in `each'
  from /Users/yossef/.rvm/gems/ruby-1.8.7-p249/gems/optitron-0.1.5/lib/optitron/parser.rb:43:in `parse_options'
  from /Users/yossef/.rvm/gems/ruby-1.8.7-p249/gems/optitron-0.1.5/lib/optitron/parser.rb:36:in `parse'
  from /Users/yossef/.rvm/gems/ruby-1.8.7-p249/gems/optitron-0.1.5/lib/optitron/class_dsl.rb:179:in `dispatch'
  from ./blah.rb:36
```

**Comment by joshbuddy** [comment]
Fixed in 0.1.6.
